name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]
        svelte: [
          3.49.x,
          3.48.x,
          3.47.x,
          3.46.x,
          3.45.x,
          3.44.x,
          3.43.x,
          3.42.x
        ]
        fontawesome-svg-core: [
          1.2.x,
          6.x
        ]
        free-solid-svg-icons: [
          5.x,
          6.x
        ]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm install --no-save svelte@${{ matrix.svelte }}
          npm install --no-save @fortawesome/fontawesome-svg-core@${{ matrix.fontawesome-svg-core }} @fortawesome/free-solid-svg-icons@${{ matrix.free-solid-svg-icons }}
          npm list svelte @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons
          npm run lint
          npm run test
      - name: dist
        run: |
          npm run dist
